### ISSUE TITLE
Add a `--dry-run` option for `prepare-release`

### ISSUE THREAD

**Issue by mrjones2014** [yaclt/yaclt#128]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to preview changes to CHANGELOG.md without writing them yet.

**Describe the solution you'd like**
We should be able to pass `--dry-run` to `prepare-release` and have it just print the changes that would be made, instead of writing them. Should look like:

```
Files to be deleted:
- list
- of
- files

CHANGELOG.md changes:

[added text here]

```

`--dry-run` should imply at least `LogLevel.normal` (which means updating the LogLevel middleware).

**Comment by mrjones2014** [comment]
This should be handled by using the `Logger` to output a multiline string.

The generation of the string should be handled by a utility function, or possibly a set of multiple utility functions. I could see this implemented with the following utilities:

- a `getChangelogEntryFilenames` utility function in `file-utils.ts` to give the list of files to be deleted
- a `dryRunTemplate` function which takes the list of files from the above function, and the generated `CHANGELOG.md` additions as parameters, and generates the output listed in the above comment via a handlebars template, something like the following:

```hbs
Files to be deleted:
{{#each filesToBeDeleted}}
- {{this}}
{{/each}}

{{globalChangelogFilename}} changes:

{{globalChangelogAdditions}}
```

**Comment by mitchellss** [comment]
I can take this issue. If --dryRun implies LogLevel.normal should a contradictory error be thrown if the --quiet option is also passed?

**Comment by mrjones2014** [comment]
Couple things, casing should be `--dry-run` not `--dryRun`. Also, it should imply a log level _greater than or equal to_ normal, i.e. you should still be able to use `--verbose` but `--silent` doesn't really make sense to use with `--dry-run`.
