### ISSUE TITLE
Add unit tests using Jest

### ISSUE THREAD

**Issue by mrjones2014** [yaclt/yaclt#30]
We should add unit tests using Jest. There currently are no tests.

This might involve extracting some of the logic into utility functions in order to test those utility functions.

**Comment by vishal-codes** [comment]
> We should add unit tests using Jest. There currently are no tests.
> 
> This might involve extracting some of the logic into utility functions in order to test those utility functions.

I have never written tests before but after reading this issue I watched a video about testing and how to write unit tests, so I think I can give this issue a shot but I'll also require some help and guidance. If this sounds good then u can assign this issue to me

**Comment by mrjones2014** [comment]
@vishal-codes sounds good. If you submit a PR we can help get it into a good state. Most likely you'll need to refactor some stuff to smaller units of work. You will also need to figure out how to mock the `fs` module (filesystem). Let me know if that sounds too complex for you.

**Comment by mrjones2014** [comment]
The more I think about this, I think it will be quite a bit of refactoring, and more complex than originally thought.

**Comment by vishal-codes** [comment]
> The more I think about this, I think it will be quite a bit of refactoring, and more complex than originally thought.

Yes

**Comment by Srimathi-S** [comment]
Can I take this up and start adding tests incrementally ?

**Comment by mrjones2014** [comment]
@Srimathi-S sure, likely it will require some refactoring of some core modules to be more testable.

**Comment by Srimathi-S** [comment]
@mrjones2014 Yes that is why thought of an incremental approach.

**Comment by Srimathi-S** [comment]
@mrjones2014 added test for two files in utility. Once this is reviewed will consider adding more and more on incremental basis.

**Comment by mrjones2014** [comment]
@Srimathi-S re-opening so that we can add more tests.

**Comment by Srimathi-S** [comment]
@mrjones2014 You can un assign me from this issue now so that someone else can take it up. Thanks for your guidance and patience throughout my contribution to your repo.
